---

name: Configs

on:
  push:
    branches:
      - main
    paths:
      - dags/**
      - plugins/**

jobs:
  copy-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Google Cloud Utilities
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true
      - name: Copy DAGs
        run: gsutil cp -r ./dags gs://${{ secrets.GCLOUD_BUCKET_PATH }}/dags
      - name: Copy plugins
        run: gsutil cp -r ./plugins gs://${{ secrets.GCLOUD_BUCKET_PATH }}/plugins
